### ISSUE TITLE
Navigation bar and footer

### ISSUE THREAD

**Issue by kimpiffy** [kimjev-webdev/Unit1#1]
**User Story**

As a recruiter, I want to see a clear, well-structured site with intuitive navigation, so I can easily assess Kim’s understanding of UX/UI principles and her approach to design.

**Acceptance Criteria**

- [x] Simple and slick navigation bar that is responsive to different devices.
- [x] An impactful homepage with hero image/carousel showcasing Kim’s art and her style.   
- [x] A footer which aids the user experience, and includes newsletter/email sign up field. 

**Tasks**

- [x] Make GitHub repository.
- [x] Make index.html in GitHub add boiler plate code.
- [x] Make the style.css page and link.
- [x] Add bootstrap.
- [x] Bootstrap navigation bar.
- [x] Bootstrap footer.
- [x] Add images for carousel.
- [x] Bootstrap carousel.
- [x] Bootstrap text and button.
