### ISSUE TITLE
Homepage carousel and styling

### ISSUE THREAD

**Issue by kimpiffy** [kimjev-webdev/Unit1#2]
**User Story**

As a prospective client, I want to view smooth and interactive web elements so I can gauge the developer's technical skills and creativity.

**Acceptance Criteria**

- [x] Dynamic hero imagery. 
- [x] Use of colour which compliments Kim’s artwork.
- [x] Text accompanying on hero image/carousel which offers information about Kim’s style.
- [x] Call to action ‘Learn More’ on carousel overlay.
- [x] Stylish buttons and navigation aided by colour changing roll over. 
- [x] Interesting fonts which compliments Kim’s artistic style.

**Tasks**

- [x] Select, optimize and upload images for the carousel. 
- [x] Generate colour palette from hero images.
- [x] Style the carousel and text/button so it has an overlay.
- [x] Style buttons so they change colour when hovered or clicked.
- [x] Remove edges and background from buttons.
- [x] Upload custom fonts and implement.
