### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by kimpiffy** [kimjev-webdev/Unit1#3]
**User Story**

As a potential collaborator, I want to find a contact form or email link easily, so I can reach out to discuss possible partnerships or freelance opportunities.

**Acceptance Criteria**

- [x] Clear link to ‘contact’ page in the navigation.
- [x] Dynamic and simple contact form.
- [x] -When completed the form displays a direct email incase they want to reach out immediately or share extra info not included in the form. 
- [x] Call to action ‘email’ sign up button in the footer. 

**Tasks**

- [x] Create contact.html page.
- [x] Bootstrap contact form.
- [x] Customise with following fields: name, email (mandatory), number (*have omitted message for personal first point of communication preferences. User has option to share their number in the message field. Keeps the form concise and short to fill in) message text input (optional), nature of query drop down menu (optional) newsletter sign up checkbox.
- [x] Edit HTML/styling so that contact email pops up after filling out the form. 
- [x] Style fields with appropriate fonts.
- [x] Style buttons.
