### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by kimpiffy** [kimjev-webdev/Unit1#4]
**User Story**

As an art enthusiast, I want to browse through a gallery of the artist's work, so I can see the artist’s style and creative range.

**Acceptance Criteria**

- [x] High quality images.
- [x] A variety of images and content.
- [x] Overall gallery should give an idea of style and skills.

**Tasks** 

- [x] Make gallery.html page.
- [x] Bootstrap Masonry tiles. 
- [x] Upload images to project.
- [x] Organise HTML for all images. 
- [x] Make gallery responsive.
- [x] Check and add alt text for visually impaired.
