### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by kimpiffy** [kimjev-webdev/Unit1#5]
**User Story**

As a potential employer I want to view Kim’s past credentials and get an in depth look at her professional profile so I can make an informed decision on whether or not to invite her to an interview. 

**Acceptance Criteria**

- [x] Biography about Kim and (maybe) a picture.
- [x] Downloadable CV.
- [x] Prompt to look at visuals/gallery.

**Tasks**

- [x] Create about.html page.
- [x] Format paragraph for biography.
- [x] Option to add profile/portrait image.
- [x] Call to action button to download CV should download C.V as a PDF.
- [x] Call to action button to view gallery, should link to gallery page.
