### ISSUE TITLE
Call to action

### ISSUE THREAD

**Issue by kimpiffy** [kimjev-webdev/Unit1#6]
As a first-time visitor, I want to see clear calls-to-action which will guide me toward contacting Kim for appropriate web development or creative projects.

**Acceptance Criteria**

- [x] Calls to action on each page guide the user through each page of the website. 
- [x] Learn more button on homepage guides to about page.
- [x] Download C.V and view my work buttons on About page. 
- [ ] Get in touch button on gallery page leads to contact page. 

**Tasks**

- [x] Bootstrap buttons on each page.
- [x] Hyperlink buttons to appropriate pages.
- [x] Style buttons appropriately - clearly a call to action.
