### ISSUE TITLE
Social links

### ISSUE THREAD

**Issue by kimpiffy** [kimjev-webdev/Unit1#7]
**User Story**

As a student, I want to research and gather information on Kim’s artistic career to get an in-depth look at her credentials, creative process and web development techniques so that I can learn from her experiences.

**Acceptance Criteria**

- [x] Social media icons, Linked In and Instagram.
- [x] Email/Newsletter sign up field.

**Tasks**

- [x] Call to action email/newsletter field in footer.
- [x] Font awesome integration in header of each page. 
- [x] Instagram and Linked in icons in footer which open in a new tab. 
- [x] Option to contact directly via contact form.
